apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: application.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="dev",container!="",image!=""}[5m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace="dev"}) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "{{ $labels.pod }} high CPU usage"
            description: "CPU usage > 80% for 5m"
        - alert: ExcessivePodRestarts
          expr: increase(kube_pod_container_status_restarts_total{namespace="dev"}[10m]) > 3
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "{{ $labels.pod }} restarted frequently"
            description: "More than 3 restarts within 10 minutes"
