# Production values for frontend.
replicaCount: 3

ingress:
  hosts:
    - host: team-notes.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
