# Image configuration

global:
  repositoryOwner: mrthehavok

image:
  # The repository is set to ghcr.io/<OWNER>/k8s-advanced-webapp-frontend
  # The <OWNER> placeholder is replaced by the CI/CD pipeline with the actual GitHub repository owner.
  # The image tag is updated by the image-updater component in the cluster, which tracks the latest
  # container image digest from the repository.
  repository: "k8s-advanced-webapp-frontend"
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
  hosts:
    - host: "" # Empty string means any host
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix

# HPA configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# Resource configuration
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

# Config for runtime environment
config:
  enabled: false
  data: {}

# Probes
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Additional configurations
nodeSelector: {}
tolerations: []
affinity: {}
extraEnv: []

# Service account settings
serviceAccount:
  create: true
  name: ""
