apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "devops@example.com" # This should be parameterized in a real environment
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - dns01:
          route53:
            region: # To be patched by overlay
