controller:
  # Use Deployment instead of DaemonSet for Fargate compatibility
  kind: Deployment

  # Tolerations for Fargate nodes
  tolerations:
    - key: eks.amazonaws.com/compute-type
      value: fargate
      effect: NoSchedule

  # Service configuration - this will create an NLB
  service:
    type: LoadBalancer
    annotations:
      # Use Network Load Balancer which works better with Fargate
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      # External traffic policy to preserve source IPs
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # Cross-zone load balancing
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

  # Resource limits for Fargate
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Autoscaling
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # Ingress class to use
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  # Admission webhooks need to be disabled on Fargate
  admissionWebhooks:
    enabled: false

  # Metrics for monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

# Don't install default backend
defaultBackend:
  enabled: false

# Service account
serviceAccount:
  create: true
