apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.4" # Use a specific version for reproducibility
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 15m
  releaseName: cert-manager
  values:
    installCRDs: true

    serviceAccount:
      create: true
      name: cert-manager
      annotations: {} # To be patched by overlay with IRSA role

    # Fargate compatibility
    securityContext:
      fsGroup: 1001

    # DNS-01 solver configuration
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53

    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

    webhook:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi

    cainjector:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
