apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/mrthehavok/k8s-advanced-webapp.git" # AIDEV-TODO: This should be dynamically discovered
    path: charts/frontend
    targetRevision: HEAD
    helm:
      releaseName: frontend
      values: |
        global:
          repositoryOwner: mrthehavok
        image:
          repository: "k8s-advanced-webapp-frontend"
          tag: latest
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
          targetPort: 80
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/healthcheck-path: /
            cert-manager.io/cluster-issuer: letsencrypt-prod
            cert-manager.io/acme-challenge-type: dns01
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          hosts:
            - host: team-notes.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: frontend-tls
              hosts:
                - team-notes.example.com
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 60
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        serviceAccount:
          create: true
          name: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
