apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.2.0 # AIDEV-NOTE: Pin to a specific version for stability
    helm:
      values: |
        # AIDEV-NOTE: This is a stub values file for the kube-prometheus-stack Helm chart.
        # It's intentionally minimal to start. We will add more configuration as needed.

        # Global settings
        global:
          # The namespace where the monitoring stack will be deployed.
          namespace: monitoring

        # Grafana configuration
        grafana:
          # We are disabling the default ingress for now. We will manage it separately.
          ingress:
            enabled: false

        # Resource limits for the various components.
        # AIDEV-TODO: Tune these resource limits based on cluster size and load. (T-11)
        kube-state-metrics:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

        prometheus-node-exporter:
          enabled: false

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
