# [task-3]
name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "services/backend/**"
  pull_request:
    branches: [main]
    paths:
      - "services/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: poetry run pytest --cov=app --cov-report=term-missing
