# [task-4]
name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "services/frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "services/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: your-docker-hub-username/frontend-app # Replace with your Docker Hub username
          tags: |
            type=sha
