# [task-6]
name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "services/frontend/**"
      - "charts/frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "services/frontend/**"
      - "charts/frontend/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint frontend Helm chart
        run: |
          helm lint charts/frontend
          helm lint charts/frontend -f charts/frontend/values-dev.yaml
          helm lint charts/frontend -f charts/frontend/values-prod.yaml
