# [task-4]
name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "services/frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "services/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/frontend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}
